### ISSUE TITLE
No trace when multithreading

### ISSUE THREAD

**Issue by jenrik** [d-e-s-o/test-env-log#6]
Tracing events are only emitted on the main thread of a test. If a test spawn another thread that produces traces, these traces will be lost.

This error is due to how tracing are initialized. Instead of only [setting a thread local trace collector](https://github.com/d-e-s-o/test-env-log/blob/f7897fad5e0c442b6f7af479b0a0c6def003b7df/src/lib.rs#L97) using `::tracing::subscriber::set_default`, a global collector needs to be configured using `set_global_default`.

**Comment by d-e-s-o** [comment]
Do you have an example handy where it fails?

**Comment by jenrik** [comment]
using the command `RUST_LOG=trace cargo test` with the below example reproduces the bug.

`src/main.rs`:
```rust
extern crate tracing;
extern crate tracing_subscriber;

use tracing::warn;

fn main() {
    println!("Hello, world!");
}

#[test_env_log::test]
fn test_multithreaded() {
    warn!("this is the main thread");

    std::thread::spawn(|| {
        warn!("this is another thread");
    });

    print!("test");
}
```

`Cargo.toml`:
```toml
[package]
name = "test-env-log_bug"
version = "0.1.0"
edition = "2018"

[dependencies]
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
env_logger = "0.8.2"
test-env-log = { version = "0.2.2", features = ["trace"] }
```
